### ISSUE TITLE
При указании параметра "additionalProperties": false typescript выдает ошибку в файле index.ts

### ISSUE THREAD

**Issue by Sergey-Baranenkov** [lad-tech/nsc-toolkit#44]
## Expected Behavior
Сервис должен сгенерироваться без ошибок

## Current Behavior
Успешно генерируется интерфейс LoginRequest

```
/**
 * Данный файл сгенерирован автоматически. Для модификации интерфейсов исправьте схему сервиса
 */
export interface LoginRequest {
  login: string;
  password: string;
}

export type LoginResponse =
  | {
      a?: string;
      [k: string]: unknown;
    }
  | {
      b?: number;
      [k: string]: unknown;
    };
```
Однако в файле index.ts typescript находит ошибку в передаваемом в request параметре payload метода login
```
TS2345: Argument of type 'LoginRequest' is not assignable to parameter of type 'RequestData'.   Type 'LoginRequest' is not assignable to type 'Record<string, unknown>'.     Index signature for type 'string' is missing in type 'LoginRequest'.
```

## Steps to Reproduce
1. Создать файл service.json с содержимым
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "name": "Auth",
  "description": "test",
  "methods": {
    "Login": {
      "action": "login",
      "description": "test",
      "request": {
        "type": "object",
        "properties": {
          "login": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": ["login", "password"]
      },
      "response": {
        "type": "object",
        "oneOf" : [
          {
            "type":  "object",
            "properties": {
              "a": {
                "type": "string"
              }
            }
          },
          {
            "type":  "object",
            "properties": {
              "b": {
                "type": "number"
              }
            }
          }
        ]
      }
    }
  }
}
```
2. Выполнить команду npx nsc-cli --schema service.json
3. Сервис генерируется, но в файле index.ts ошибка тайпскрипта

## Context (Environment)
- Linux version 6.1.19-1-MANJARO
- Nodejs v18.15.0

## Detailed Description
Необхдимо добавить поддержку "additionalProperties": false, чтобы запретить возможность передавать в метод свойства, не указанные в контракте

**Comment by gleip** [comment]
@Sergey-Baranenkov По моему ты ошибся репозиторием ) Ишка для https://github.com/lad-tech/nsc-cli

**Comment by Sergey-Baranenkov** [comment]
Не совсем понял из ответа, если я включу runTimeValidation, но additionalProperties: true, то, если передам лишние поля, валидатор заругается?

**Comment by gleip** [comment]
@Sergey-Baranenkov Если включешь runTimeValidation и в схеме будет указан флаг additionalProperties: false и при этом будет передан объект с полем, которого нет в схеме то получишь ошибку валидации в рантайме. Если будет стоять флаг в схеме additionalProperties: true то ошибки не будет. Ну и тут в приницпе можно использовать весь функционал схем. Например передать в  "additionalProperties": { "type": "string" } и тогда можно будет добавлять ключи, которых нет в схеме, только со строковыми значениями. Перетащить такой функционал из рантайма в тс не получится.

**Comment by Sergey-Baranenkov** [comment]
Я жеж говорю, если я включю runTimeValidation: true и additionalProperties: false то в файле index.ts будет ошибка из-за несоответствия типов. Эта ошибка появляется независимо от поля runTimeValidation

**Comment by gleip** [comment]
@Sergey-Baranenkov @Blynskyniki  Да. Тут соль в том, что тип входных параметров для метода ограничен вот так `Record<string, unknown>`. Получается что мы можем передать только объект. Ошибка возникает потому, что nsc-cli в зависимости от флага additionalProperties генерирует либо индексный тип либо нет. Поскольку Record это индексный тип то не индексный обычный interface вызывает ошибку. На мой взгляд все генерируемые типы в nsc-cli должны быть индексными. Поскольку на уровне ТС мы не можем полноценно контролировать избыточность свойств объекта из-за структурной типизации языка. Есть дополнительные проверки на стороне ТС но они относятся только к объектным литералам. Если nsc-cli будет генерировать и индексные типы и не индексные то на стороне nsc-toolkit, чтобы исправить ошибку нужно будет поменять  Record<string, unknown> на просто unknown. Ошибка пропадет но тогда это позволит вызывать методы не только с объектными параметрами но и с примитивами, а это на мой взгляд плохо. Так что я бы все же поменял генерацию и всегда генерировал индексные типы, ну а если потребуется ограничить набор свойств объекта то делать это можно в рантайме с помощью валидации и флага additionalProperties.
